api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api/

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
